import '../modelos/palabra_hablada.dart';

/// Todo lo que se puede practicar, junto. La pantalla lo separa por grupo.
List<PalabraHablada> get palabrasParaDecir => [
      ...sonidosParaDecir,
      ...numerosParaDecir,
      ...frasesParaDecir,
    ];

/// Las palabras agrupadas por el sonido que el castellano hace pronunciar mal.
///
/// Son todas palabras de uso diario: la idea es que practicar el sonido sirva
/// también para acordarse de la palabra. El sonido de cada una se muestra en
/// la tarjeta, así se ve qué es lo que hay que mirar.
///
/// Van escritas acá y no en un JSON porque el contenido todavía se está
/// armando. Cuando se asiente pasan al JSON como el resto, y ahí se pueden
/// agregar sin sacar un APK nuevo.
const List<PalabraHablada> sonidosParaDecir = [
  PalabraHablada(
    italiano: 'cinque',
    espanol: 'cinco',
    pista: 'chín-cue',
    sonido: 'ci = ch',
  ),
  PalabraHablada(
    italiano: 'ciao',
    espanol: 'hola, chau',
    pista: 'cháo',
    sonido: 'ci = ch',
  ),
  PalabraHablada(
    italiano: 'dolce',
    espanol: 'dulce, postre',
    pista: 'dól-che',
    sonido: 'ce = che',
  ),
  PalabraHablada(
    italiano: 'cena',
    espanol: 'cena',
    pista: 'ché-na',
    sonido: 'ce = che',
  ),
  PalabraHablada(
    italiano: 'felice',
    espanol: 'feliz',
    pista: 'fe-lí-che',
    sonido: 'ce = che',
  ),
  PalabraHablada(
    italiano: 'cioccolato',
    espanol: 'chocolate',
    pista: 'cho-co-lá-to',
    sonido: 'ci = ch',
  ),
  PalabraHablada(
    italiano: 'arrivederci',
    espanol: 'hasta luego',
    pista: 'a-rri-ve-dér-chi',
    sonido: 'ci = ch',
  ),
  PalabraHablada(
    italiano: 'bacio',
    espanol: 'beso',
    pista: 'bá-cho',
    sonido: 'ci = ch',
  ),
  PalabraHablada(
    italiano: 'città',
    espanol: 'ciudad',
    pista: 'chit-tá',
    sonido: 'ci = ch',
  ),
  PalabraHablada(
    italiano: 'chiesa',
    espanol: 'iglesia',
    pista: 'quié-sa',
    sonido: 'chi = qui',
  ),
  PalabraHablada(
    italiano: 'perché',
    espanol: 'por qué, porque',
    pista: 'per-qué',
    sonido: 'che = que',
  ),
  PalabraHablada(
    italiano: 'chiave',
    espanol: 'llave',
    pista: 'quiá-ve',
    sonido: 'chi = qui',
  ),
  PalabraHablada(
    italiano: 'bicchiere',
    espanol: 'vaso',
    pista: 'bic-quié-re',
    sonido: 'chi = qui',
  ),
  PalabraHablada(
    italiano: 'anche',
    espanol: 'también',
    pista: 'án-que',
    sonido: 'che = que',
  ),
  PalabraHablada(
    italiano: 'macchina',
    espanol: 'auto',
    pista: 'mác-qui-na',
    sonido: 'chi = qui',
  ),
  PalabraHablada(
    italiano: 'amiche',
    espanol: 'amigas',
    pista: 'a-mí-que',
    sonido: 'che = que',
  ),
  PalabraHablada(
    italiano: 'gnocchi',
    espanol: 'ñoquis',
    pista: 'ñó-qui',
    sonido: 'gn = ñ',
  ),
  PalabraHablada(
    italiano: 'signora',
    espanol: 'señora',
    pista: 'si-ñó-ra',
    sonido: 'gn = ñ',
  ),
  PalabraHablada(
    italiano: 'bagno',
    espanol: 'baño',
    pista: 'bá-ño',
    sonido: 'gn = ñ',
  ),
  PalabraHablada(
    italiano: 'montagna',
    espanol: 'montaña',
    pista: 'mon-tá-ña',
    sonido: 'gn = ñ',
  ),
  PalabraHablada(
    italiano: 'compagno',
    espanol: 'compañero',
    pista: 'com-pá-ño',
    sonido: 'gn = ñ',
  ),
  PalabraHablada(
    italiano: 'lasagne',
    espanol: 'lasaña',
    pista: 'la-zá-ñe',
    sonido: 'gn = ñ',
  ),
  PalabraHablada(
    italiano: 'sogno',
    espanol: 'sueño',
    pista: 'só-ño',
    sonido: 'gn = ñ',
  ),
  PalabraHablada(
    italiano: 'famiglia',
    espanol: 'familia',
    pista: 'fa-mí-lia, con la lengua contra el paladar',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'figlio',
    espanol: 'hijo',
    pista: 'fí-lio',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'aglio',
    espanol: 'ajo',
    pista: 'á-lio',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'moglie',
    espanol: 'esposa',
    pista: 'mó-lie',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'meglio',
    espanol: 'mejor',
    pista: 'mé-lio',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'biglietto',
    espanol: 'boleto, entrada',
    pista: 'bi-liét-to',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'luglio',
    espanol: 'julio',
    pista: 'lú-lio',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'voglio',
    espanol: 'quiero',
    pista: 'vó-lio',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'pesce',
    espanol: 'pescado',
    pista: 'pé-she',
    sonido: 'sce = sh',
  ),
  PalabraHablada(
    italiano: 'sciare',
    espanol: 'esquiar',
    pista: 'shá-re',
    sonido: 'sci = sh',
  ),
  PalabraHablada(
    italiano: 'uscita',
    espanol: 'salida',
    pista: 'u-shí-ta',
    sonido: 'sci = sh',
  ),
  PalabraHablada(
    italiano: 'prosciutto',
    espanol: 'jamón crudo',
    pista: 'pro-shút-to',
    sonido: 'sci = sh',
  ),
  PalabraHablada(
    italiano: 'conoscere',
    espanol: 'conocer',
    pista: 'co-nó-she-re',
    sonido: 'sce = sh',
  ),
  PalabraHablada(
    italiano: 'asciugamano',
    espanol: 'toalla',
    pista: 'a-shu-ga-má-no',
    sonido: 'sci = sh',
  ),
  PalabraHablada(
    italiano: 'scuola',
    espanol: 'escuela',
    pista: 'scuó-la, sin la e de adelante',
    sonido: 'sc = sk',
  ),
  PalabraHablada(
    italiano: 'scusa',
    espanol: 'perdón',
    pista: 'scú-sa, sin la e de adelante',
    sonido: 'sc = sk',
  ),
  PalabraHablada(
    italiano: 'scarpe',
    espanol: 'zapatos',
    pista: 'scár-pe, sin la e de adelante',
    sonido: 'sc = sk',
  ),
  PalabraHablada(
    italiano: 'bosco',
    espanol: 'bosque',
    pista: 'bós-co',
    sonido: 'sc = sk',
  ),
  PalabraHablada(
    italiano: 'fresco',
    espanol: 'fresco',
    pista: 'frés-co',
    sonido: 'sc = sk',
  ),
  PalabraHablada(
    italiano: 'maschera',
    espanol: 'máscara',
    pista: 'más-que-ra',
    sonido: 'sc = sk',
  ),
  PalabraHablada(
    italiano: 'nonna',
    espanol: 'abuela',
    pista: 'nón-na, con la n larga',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'anno',
    espanol: 'año',
    pista: 'án-no, con la n larga',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'bello',
    espanol: 'lindo',
    pista: 'bél-lo, con la l larga',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'terra',
    espanol: 'tierra',
    pista: 'tér-ra',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'mamma',
    espanol: 'mamá',
    pista: 'mám-ma',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'freddo',
    espanol: 'frío',
    pista: 'fréd-do',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'cappuccino',
    espanol: 'capuchino',
    pista: 'cap-put-chí-no',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'spaghetti',
    espanol: 'espaguetis',
    pista: 'spa-guét-ti',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'grazie',
    espanol: 'gracias',
    pista: 'grá-tsie',
    sonido: 'z = ts',
  ),
  PalabraHablada(
    italiano: 'pizza',
    espanol: 'pizza',
    pista: 'pít-tsa',
    sonido: 'zz = ts',
  ),
  PalabraHablada(
    italiano: 'piazza',
    espanol: 'plaza',
    pista: 'piát-tsa',
    sonido: 'zz = ts',
  ),
  PalabraHablada(
    italiano: 'stazione',
    espanol: 'estación',
    pista: 'sta-tsió-ne',
    sonido: 'z = ts',
  ),
  PalabraHablada(
    italiano: 'ragazzo',
    espanol: 'chico',
    pista: 'ra-gát-tso',
    sonido: 'zz = ts',
  ),
  PalabraHablada(
    italiano: 'colazione',
    espanol: 'desayuno',
    pista: 'co-la-tsió-ne',
    sonido: 'z = ts',
  ),
  PalabraHablada(
    italiano: 'zucchero',
    espanol: 'azúcar',
    pista: 'dzúc-que-ro',
    sonido: 'z = ds',
  ),
  PalabraHablada(
    italiano: 'zio',
    espanol: 'tío',
    pista: 'dzí-o',
    sonido: 'z = ds',
  ),
  PalabraHablada(
    italiano: 'treno',
    espanol: 'tren',
    pista: 'tré-no',
    sonido: 'r fuerte',
  ),
  PalabraHablada(
    italiano: 'birra',
    espanol: 'cerveza',
    pista: 'bír-ra',
    sonido: 'r fuerte',
  ),
  PalabraHablada(
    italiano: 'arrivare',
    espanol: 'llegar',
    pista: 'a-rri-vá-re',
    sonido: 'r fuerte',
  ),
  PalabraHablada(
    italiano: 'parlare',
    espanol: 'hablar',
    pista: 'par-lá-re',
    sonido: 'r fuerte',
  ),
  PalabraHablada(
    italiano: 'ghiaccio',
    espanol: 'hielo',
    pista: 'guiác-cho',
    sonido: 'gh = gu',
  ),
  PalabraHablada(
    italiano: 'funghi',
    espanol: 'hongos',
    pista: 'fún-gui',
    sonido: 'gh = gu',
  ),
  PalabraHablada(
    italiano: 'lunghi',
    espanol: 'largos',
    pista: 'lún-gui',
    sonido: 'gh = gu',
  ),
];

/// Los números del 0 al 30.
///
/// Son los que más se dicen en voz alta de verdad —la hora, el precio, el
/// número de la casa— y de paso repasan medio abecedario de sonidos raros:
/// zero empieza con la z italiana, dieci y undici llevan el "chi", quattro y
/// sette la doble consonante, ventuno y ventotto se comen la i de venti.
const List<PalabraHablada> numerosParaDecir = [
  PalabraHablada(
    italiano: 'zero',
    espanol: 'cero',
    pista: 'dzé-ro',
    sonido: '0',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'uno',
    espanol: 'uno',
    pista: 'ú-no',
    sonido: '1',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'due',
    espanol: 'dos',
    pista: 'dú-e, en dos golpes',
    sonido: '2',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'tre',
    espanol: 'tres',
    pista: 'tre, con la r bien marcada',
    sonido: '3',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'quattro',
    espanol: 'cuatro',
    pista: 'cuát-tro, apoyando la doble t',
    sonido: '4',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'cinque',
    espanol: 'cinco',
    pista: 'chín-cue',
    sonido: '5',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'sei',
    espanol: 'seis',
    pista: 'séi',
    sonido: '6',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'sette',
    espanol: 'siete',
    pista: 'sét-te, apoyando la doble t',
    sonido: '7',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'otto',
    espanol: 'ocho',
    pista: 'ót-to, apoyando la doble t',
    sonido: '8',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'nove',
    espanol: 'nueve',
    pista: 'nó-ve',
    sonido: '9',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'dieci',
    espanol: 'diez',
    pista: 'dié-chi',
    sonido: '10',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'undici',
    espanol: 'once',
    pista: 'ún-di-chi',
    sonido: '11',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'dodici',
    espanol: 'doce',
    pista: 'dó-di-chi',
    sonido: '12',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'tredici',
    espanol: 'trece',
    pista: 'tré-di-chi',
    sonido: '13',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'quattordici',
    espanol: 'catorce',
    pista: 'cuat-tór-di-chi',
    sonido: '14',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'quindici',
    espanol: 'quince',
    pista: 'cuín-di-chi',
    sonido: '15',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'sedici',
    espanol: 'dieciséis',
    pista: 'sé-di-chi',
    sonido: '16',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'diciassette',
    espanol: 'diecisiete',
    pista: 'di-chas-sét-te',
    sonido: '17',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'diciotto',
    espanol: 'dieciocho',
    pista: 'di-chót-to',
    sonido: '18',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'diciannove',
    espanol: 'diecinueve',
    pista: 'di-chan-nó-ve',
    sonido: '19',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'venti',
    espanol: 'veinte',
    pista: 'vén-ti',
    sonido: '20',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventuno',
    espanol: 'veintiuno',
    pista: 'ven-tú-no, sin la i',
    sonido: '21',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventidue',
    espanol: 'veintidós',
    pista: 'ven-ti-dú-e',
    sonido: '22',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventitré',
    espanol: 'veintitrés',
    pista: 'ven-ti-tré',
    sonido: '23',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventiquattro',
    espanol: 'veinticuatro',
    pista: 'ven-ti-cuát-tro',
    sonido: '24',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'venticinque',
    espanol: 'veinticinco',
    pista: 'ven-ti-chín-cue',
    sonido: '25',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventisei',
    espanol: 'veintiséis',
    pista: 'ven-ti-séi',
    sonido: '26',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventisette',
    espanol: 'veintisiete',
    pista: 'ven-ti-sét-te',
    sonido: '27',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventotto',
    espanol: 'veintiocho',
    pista: 'ven-tót-to, sin la i',
    sonido: '28',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventinove',
    espanol: 'veintinueve',
    pista: 'ven-ti-nó-ve',
    sonido: '29',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'trenta',
    espanol: 'treinta',
    pista: 'trén-ta',
    sonido: '30',
    grupo: GrupoHabla.numeros,
  ),
];

/// Frases enteras, para practicar el ritmo y no solo la palabra suelta.
///
/// Son de las que se usan de verdad —pedir algo, no entender, moverse— y de
/// largo suficiente para que haya que sostener el ritmo, no solo acertar una
/// palabra.
/// Ninguna lleva apóstrofo a propósito ("dov'è"): el reconocedor a veces lo
/// escribe separado y la palabra no coincidiría por un detalle que no tiene
/// nada que ver con la pronunciación.
const List<PalabraHablada> frasesParaDecir = [
  PalabraHablada(
    italiano: 'Buongiorno, vorrei un caffè e un cornetto, per favore.',
    espanol: 'Buen día, quisiera un café y una medialuna, por favor.',
    pista: 'buon-yór-no, caf-fé',
    sonido: 'en el bar',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Scusi, mi può dire dove si trova la stazione?',
    espanol: 'Perdón, ¿me puede decir dónde queda la estación?',
    pista: 'scú-si, sta-tsió-ne',
    sonido: 'moverse',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Non capisco molto bene, può ripetere più lentamente?',
    espanol: 'No entiendo muy bien, ¿puede repetir más despacio?',
    pista: 'ca-pís-co, ri-pé-te-re',
    sonido: 'no entender',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Mi chiamo Marco e sono venuto in Italia per studiare.',
    espanol: 'Me llamo Marco y vine a Italia a estudiar.',
    pista: 'quiá-mo, no chiamo',
    sonido: 'presentarse',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Vorrei prenotare un tavolo per due persone alle otto.',
    espanol: 'Quisiera reservar una mesa para dos personas a las ocho.',
    pista: 'pre-no-tá-re, ót-to',
    sonido: 'en la mesa',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Quanto costa il biglietto del treno per andare a Roma?',
    espanol: '¿Cuánto cuesta el boleto de tren para ir a Roma?',
    pista: 'bi-liét-to, tré-no',
    sonido: 'moverse',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'La mia famiglia è argentina, ma i miei nonni erano italiani.',
    espanol: 'Mi familia es argentina, pero mis abuelos eran italianos.',
    pista: 'fa-mí-lia, nón-ni',
    sonido: 'la familia',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Domani mattina andiamo in montagna se non fa troppo freddo.',
    espanol: 'Mañana a la mañana vamos a la montaña si no hace mucho frío.',
    pista: 'mon-tá-ña, fréd-do',
    sonido: 'planes',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Questo formaggio è buonissimo, dove lo posso comprare?',
    espanol: 'Este queso está riquísimo, ¿dónde lo puedo comprar?',
    pista: 'for-mád-yo',
    sonido: 'en la mesa',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Il museo apre alle nove e chiude alle diciotto.',
    espanol: 'El museo abre a las nueve y cierra a las dieciocho.',
    pista: 'quiú-de, di-chót-to',
    sonido: 'moverse',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Mio figlio ha cinque anni e va a scuola in macchina.',
    espanol: 'Mi hijo tiene cinco años y va a la escuela en auto.',
    pista: 'fí-lio, chín-cue, mác-qui-na',
    sonido: 'la familia',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Vorrei una birra fredda e un piatto di prosciutto crudo.',
    espanol: 'Quisiera una cerveza fría y un plato de jamón crudo.',
    pista: 'bír-ra, pro-shút-to',
    sonido: 'en el bar',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Scusi, ho perso il treno, quando parte il prossimo?',
    espanol: 'Perdón, perdí el tren, ¿cuándo sale el próximo?',
    pista: 'la h no suena: ó pér-so',
    sonido: 'moverse',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Mi piace molto camminare per la città quando fa fresco.',
    espanol: 'Me gusta mucho caminar por la ciudad cuando está fresco.',
    pista: 'piá-che, chit-tá',
    sonido: 'planes',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Ho fame e ho sete, andiamo a mangiare qualcosa insieme?',
    espanol: 'Tengo hambre y sed, ¿vamos a comer algo juntos?',
    pista: 'mand-yá-re, in-sié-me',
    sonido: 'en la mesa',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Il conto per favore, possiamo pagare con la carta?',
    espanol: 'La cuenta por favor, ¿podemos pagar con tarjeta?',
    pista: 'cón-to, cár-ta',
    sonido: 'en el bar',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Domenica andiamo al mare con la famiglia di mia moglie.',
    espanol: 'El domingo vamos al mar con la familia de mi esposa.',
    pista: 'fa-mí-lia, mó-lie',
    sonido: 'planes',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Questa è la chiave della camera numero dodici.',
    espanol: 'Esta es la llave de la habitación número doce.',
    pista: 'quiá-ve, dó-di-chi',
    sonido: 'moverse',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Vorrei comprare due biglietti per il museo di domani.',
    espanol: 'Quisiera comprar dos entradas para el museo de mañana.',
    pista: 'bi-liét-ti, mu-sé-o',
    sonido: 'comprar',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Non conosco bene questa città, mi può aiutare per favore?',
    espanol: 'No conozco bien esta ciudad, ¿me puede ayudar por favor?',
    pista: 'co-nós-co, chit-tá',
    sonido: 'no entender',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Ogni mattina bevo un cappuccino e leggo il giornale.',
    espanol: 'Todas las mañanas tomo un capuchino y leo el diario.',
    pista: 'ó-ñi, cap-put-chí-no',
    sonido: 'planes',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Mi sono perso, sto cercando la piazza principale del centro.',
    espanol: 'Me perdí, estoy buscando la plaza principal del centro.',
    pista: 'cher-cán-do, piát-tsa',
    sonido: 'moverse',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Che ore sono? Devo prendere il treno delle sette.',
    espanol: '¿Qué hora es? Tengo que tomar el tren de las siete.',
    pista: 'que ó-re, sét-te',
    sonido: 'moverse',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Piacere di conoscerti, io sono di Buenos Aires, in Argentina.',
    espanol: 'Un gusto conocerte, yo soy de Buenos Aires, Argentina.',
    pista: 'piá-che-re, co-nó-sher-ti',
    sonido: 'presentarse',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'In estate fa molto caldo, preferisco andare in montagna.',
    espanol: 'En verano hace mucho calor, prefiero ir a la montaña.',
    pista: 'es-tá-te, mon-tá-ña',
    sonido: 'el tiempo',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Vorrei sapere se questo ristorante apre anche la domenica.',
    espanol: 'Quisiera saber si este restaurante abre también los domingos.',
    pista: 'án-que, do-mé-ni-ca',
    sonido: 'comprar',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Mia nonna faceva gli gnocchi ogni giovedì per tutta la famiglia.',
    espanol: 'Mi abuela hacía ñoquis todos los jueves para toda la familia.',
    pista: 'ñó-qui, yo-ve-dí',
    sonido: 'la familia',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Scusi, questo posto è libero? Posso sedermi qui?',
    espanol: 'Perdón, ¿este lugar está libre? ¿Me puedo sentar acá?',
    pista: 'scú-si, se-dér-mi',
    sonido: 'en la mesa',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Grazie mille per il tuo aiuto, sei stato molto gentile.',
    espanol: 'Mil gracias por tu ayuda, fuiste muy amable.',
    pista: 'grá-tsie, yen-tí-le',
    sonido: 'saludos',
    grupo: GrupoHabla.frases,
  ),
  PalabraHablada(
    italiano: 'Buonasera signora, come sta? Da quanto tempo non ci vediamo.',
    espanol: 'Buenas tardes señora, ¿cómo está? Hace cuánto que no nos vemos.',
    pista: 'buo-na-sé-ra, ve-diá-mo',
    sonido: 'saludos',
    grupo: GrupoHabla.frases,
  ),
];
