import '../modelos/palabra_hablada.dart';

/// Todo lo que se puede practicar, junto. La pantalla lo separa por grupo.
List<PalabraHablada> get palabrasParaDecir => [
      ...sonidosParaDecir,
      ...numerosParaDecir,
    ];

/// Las palabras agrupadas por el sonido que el castellano hace pronunciar mal.
///
/// Son todas palabras de uso diario: la idea es que practicar el sonido sirva
/// también para acordarse de la palabra. El sonido de cada una se muestra en
/// la tarjeta, así se ve qué es lo que hay que mirar.
///
/// Van escritas acá y no en un JSON porque el contenido todavía se está
/// armando. Cuando se asiente pasan al JSON como el resto, y ahí se pueden
/// agregar sin sacar un APK nuevo.
const List<PalabraHablada> sonidosParaDecir = [
  PalabraHablada(
    italiano: 'cinque',
    espanol: 'cinco',
    pista: 'chín-cue',
    sonido: 'ci = ch',
  ),
  PalabraHablada(
    italiano: 'ciao',
    espanol: 'hola, chau',
    pista: 'cháo',
    sonido: 'ci = ch',
  ),
  PalabraHablada(
    italiano: 'dolce',
    espanol: 'dulce, postre',
    pista: 'dól-che',
    sonido: 'ce = che',
  ),
  PalabraHablada(
    italiano: 'cena',
    espanol: 'cena',
    pista: 'ché-na',
    sonido: 'ce = che',
  ),
  PalabraHablada(
    italiano: 'felice',
    espanol: 'feliz',
    pista: 'fe-lí-che',
    sonido: 'ce = che',
  ),
  PalabraHablada(
    italiano: 'cioccolato',
    espanol: 'chocolate',
    pista: 'cho-co-lá-to',
    sonido: 'ci = ch',
  ),
  PalabraHablada(
    italiano: 'arrivederci',
    espanol: 'hasta luego',
    pista: 'a-rri-ve-dér-chi',
    sonido: 'ci = ch',
  ),
  PalabraHablada(
    italiano: 'bacio',
    espanol: 'beso',
    pista: 'bá-cho',
    sonido: 'ci = ch',
  ),
  PalabraHablada(
    italiano: 'città',
    espanol: 'ciudad',
    pista: 'chit-tá',
    sonido: 'ci = ch',
  ),
  PalabraHablada(
    italiano: 'chiesa',
    espanol: 'iglesia',
    pista: 'quié-sa',
    sonido: 'chi = qui',
  ),
  PalabraHablada(
    italiano: 'perché',
    espanol: 'por qué, porque',
    pista: 'per-qué',
    sonido: 'che = que',
  ),
  PalabraHablada(
    italiano: 'chiave',
    espanol: 'llave',
    pista: 'quiá-ve',
    sonido: 'chi = qui',
  ),
  PalabraHablada(
    italiano: 'bicchiere',
    espanol: 'vaso',
    pista: 'bic-quié-re',
    sonido: 'chi = qui',
  ),
  PalabraHablada(
    italiano: 'anche',
    espanol: 'también',
    pista: 'án-que',
    sonido: 'che = que',
  ),
  PalabraHablada(
    italiano: 'macchina',
    espanol: 'auto',
    pista: 'mác-qui-na',
    sonido: 'chi = qui',
  ),
  PalabraHablada(
    italiano: 'amiche',
    espanol: 'amigas',
    pista: 'a-mí-que',
    sonido: 'che = que',
  ),
  PalabraHablada(
    italiano: 'gnocchi',
    espanol: 'ñoquis',
    pista: 'ñó-qui',
    sonido: 'gn = ñ',
  ),
  PalabraHablada(
    italiano: 'signora',
    espanol: 'señora',
    pista: 'si-ñó-ra',
    sonido: 'gn = ñ',
  ),
  PalabraHablada(
    italiano: 'bagno',
    espanol: 'baño',
    pista: 'bá-ño',
    sonido: 'gn = ñ',
  ),
  PalabraHablada(
    italiano: 'montagna',
    espanol: 'montaña',
    pista: 'mon-tá-ña',
    sonido: 'gn = ñ',
  ),
  PalabraHablada(
    italiano: 'compagno',
    espanol: 'compañero',
    pista: 'com-pá-ño',
    sonido: 'gn = ñ',
  ),
  PalabraHablada(
    italiano: 'lasagne',
    espanol: 'lasaña',
    pista: 'la-zá-ñe',
    sonido: 'gn = ñ',
  ),
  PalabraHablada(
    italiano: 'sogno',
    espanol: 'sueño',
    pista: 'só-ño',
    sonido: 'gn = ñ',
  ),
  PalabraHablada(
    italiano: 'famiglia',
    espanol: 'familia',
    pista: 'fa-mí-lia, con la lengua contra el paladar',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'figlio',
    espanol: 'hijo',
    pista: 'fí-lio',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'aglio',
    espanol: 'ajo',
    pista: 'á-lio',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'moglie',
    espanol: 'esposa',
    pista: 'mó-lie',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'meglio',
    espanol: 'mejor',
    pista: 'mé-lio',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'biglietto',
    espanol: 'boleto, entrada',
    pista: 'bi-liét-to',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'luglio',
    espanol: 'julio',
    pista: 'lú-lio',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'voglio',
    espanol: 'quiero',
    pista: 'vó-lio',
    sonido: 'gli',
  ),
  PalabraHablada(
    italiano: 'pesce',
    espanol: 'pescado',
    pista: 'pé-she',
    sonido: 'sce = sh',
  ),
  PalabraHablada(
    italiano: 'sciare',
    espanol: 'esquiar',
    pista: 'shá-re',
    sonido: 'sci = sh',
  ),
  PalabraHablada(
    italiano: 'uscita',
    espanol: 'salida',
    pista: 'u-shí-ta',
    sonido: 'sci = sh',
  ),
  PalabraHablada(
    italiano: 'prosciutto',
    espanol: 'jamón crudo',
    pista: 'pro-shút-to',
    sonido: 'sci = sh',
  ),
  PalabraHablada(
    italiano: 'conoscere',
    espanol: 'conocer',
    pista: 'co-nó-she-re',
    sonido: 'sce = sh',
  ),
  PalabraHablada(
    italiano: 'asciugamano',
    espanol: 'toalla',
    pista: 'a-shu-ga-má-no',
    sonido: 'sci = sh',
  ),
  PalabraHablada(
    italiano: 'scuola',
    espanol: 'escuela',
    pista: 'scuó-la, sin la e de adelante',
    sonido: 'sc = sk',
  ),
  PalabraHablada(
    italiano: 'scusa',
    espanol: 'perdón',
    pista: 'scú-sa, sin la e de adelante',
    sonido: 'sc = sk',
  ),
  PalabraHablada(
    italiano: 'scarpe',
    espanol: 'zapatos',
    pista: 'scár-pe, sin la e de adelante',
    sonido: 'sc = sk',
  ),
  PalabraHablada(
    italiano: 'bosco',
    espanol: 'bosque',
    pista: 'bós-co',
    sonido: 'sc = sk',
  ),
  PalabraHablada(
    italiano: 'fresco',
    espanol: 'fresco',
    pista: 'frés-co',
    sonido: 'sc = sk',
  ),
  PalabraHablada(
    italiano: 'maschera',
    espanol: 'máscara',
    pista: 'más-que-ra',
    sonido: 'sc = sk',
  ),
  PalabraHablada(
    italiano: 'nonna',
    espanol: 'abuela',
    pista: 'nón-na, con la n larga',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'anno',
    espanol: 'año',
    pista: 'án-no, con la n larga',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'bello',
    espanol: 'lindo',
    pista: 'bél-lo, con la l larga',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'terra',
    espanol: 'tierra',
    pista: 'tér-ra',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'mamma',
    espanol: 'mamá',
    pista: 'mám-ma',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'freddo',
    espanol: 'frío',
    pista: 'fréd-do',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'cappuccino',
    espanol: 'capuchino',
    pista: 'cap-put-chí-no',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'spaghetti',
    espanol: 'espaguetis',
    pista: 'spa-guét-ti',
    sonido: 'doble consonante',
  ),
  PalabraHablada(
    italiano: 'grazie',
    espanol: 'gracias',
    pista: 'grá-tsie',
    sonido: 'z = ts',
  ),
  PalabraHablada(
    italiano: 'pizza',
    espanol: 'pizza',
    pista: 'pít-tsa',
    sonido: 'zz = ts',
  ),
  PalabraHablada(
    italiano: 'piazza',
    espanol: 'plaza',
    pista: 'piát-tsa',
    sonido: 'zz = ts',
  ),
  PalabraHablada(
    italiano: 'stazione',
    espanol: 'estación',
    pista: 'sta-tsió-ne',
    sonido: 'z = ts',
  ),
  PalabraHablada(
    italiano: 'ragazzo',
    espanol: 'chico',
    pista: 'ra-gát-tso',
    sonido: 'zz = ts',
  ),
  PalabraHablada(
    italiano: 'colazione',
    espanol: 'desayuno',
    pista: 'co-la-tsió-ne',
    sonido: 'z = ts',
  ),
  PalabraHablada(
    italiano: 'zucchero',
    espanol: 'azúcar',
    pista: 'dzúc-que-ro',
    sonido: 'z = ds',
  ),
  PalabraHablada(
    italiano: 'zio',
    espanol: 'tío',
    pista: 'dzí-o',
    sonido: 'z = ds',
  ),
  PalabraHablada(
    italiano: 'treno',
    espanol: 'tren',
    pista: 'tré-no',
    sonido: 'r fuerte',
  ),
  PalabraHablada(
    italiano: 'birra',
    espanol: 'cerveza',
    pista: 'bír-ra',
    sonido: 'r fuerte',
  ),
  PalabraHablada(
    italiano: 'arrivare',
    espanol: 'llegar',
    pista: 'a-rri-vá-re',
    sonido: 'r fuerte',
  ),
  PalabraHablada(
    italiano: 'parlare',
    espanol: 'hablar',
    pista: 'par-lá-re',
    sonido: 'r fuerte',
  ),
  PalabraHablada(
    italiano: 'ghiaccio',
    espanol: 'hielo',
    pista: 'guiác-cho',
    sonido: 'gh = gu',
  ),
  PalabraHablada(
    italiano: 'funghi',
    espanol: 'hongos',
    pista: 'fún-gui',
    sonido: 'gh = gu',
  ),
  PalabraHablada(
    italiano: 'lunghi',
    espanol: 'largos',
    pista: 'lún-gui',
    sonido: 'gh = gu',
  ),
];

/// Los números del 0 al 30.
///
/// Son los que más se dicen en voz alta de verdad —la hora, el precio, el
/// número de la casa— y de paso repasan medio abecedario de sonidos raros:
/// zero empieza con la z italiana, dieci y undici llevan el "chi", quattro y
/// sette la doble consonante, ventuno y ventotto se comen la i de venti.
const List<PalabraHablada> numerosParaDecir = [
  PalabraHablada(
    italiano: 'zero',
    espanol: 'cero',
    pista: 'dzé-ro',
    sonido: '0',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'uno',
    espanol: 'uno',
    pista: 'ú-no',
    sonido: '1',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'due',
    espanol: 'dos',
    pista: 'dú-e, en dos golpes',
    sonido: '2',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'tre',
    espanol: 'tres',
    pista: 'tre, con la r bien marcada',
    sonido: '3',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'quattro',
    espanol: 'cuatro',
    pista: 'cuát-tro, apoyando la doble t',
    sonido: '4',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'cinque',
    espanol: 'cinco',
    pista: 'chín-cue',
    sonido: '5',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'sei',
    espanol: 'seis',
    pista: 'séi',
    sonido: '6',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'sette',
    espanol: 'siete',
    pista: 'sét-te, apoyando la doble t',
    sonido: '7',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'otto',
    espanol: 'ocho',
    pista: 'ót-to, apoyando la doble t',
    sonido: '8',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'nove',
    espanol: 'nueve',
    pista: 'nó-ve',
    sonido: '9',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'dieci',
    espanol: 'diez',
    pista: 'dié-chi',
    sonido: '10',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'undici',
    espanol: 'once',
    pista: 'ún-di-chi',
    sonido: '11',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'dodici',
    espanol: 'doce',
    pista: 'dó-di-chi',
    sonido: '12',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'tredici',
    espanol: 'trece',
    pista: 'tré-di-chi',
    sonido: '13',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'quattordici',
    espanol: 'catorce',
    pista: 'cuat-tór-di-chi',
    sonido: '14',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'quindici',
    espanol: 'quince',
    pista: 'cuín-di-chi',
    sonido: '15',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'sedici',
    espanol: 'dieciséis',
    pista: 'sé-di-chi',
    sonido: '16',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'diciassette',
    espanol: 'diecisiete',
    pista: 'di-chas-sét-te',
    sonido: '17',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'diciotto',
    espanol: 'dieciocho',
    pista: 'di-chót-to',
    sonido: '18',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'diciannove',
    espanol: 'diecinueve',
    pista: 'di-chan-nó-ve',
    sonido: '19',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'venti',
    espanol: 'veinte',
    pista: 'vén-ti',
    sonido: '20',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventuno',
    espanol: 'veintiuno',
    pista: 'ven-tú-no, sin la i',
    sonido: '21',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventidue',
    espanol: 'veintidós',
    pista: 'ven-ti-dú-e',
    sonido: '22',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventitré',
    espanol: 'veintitrés',
    pista: 'ven-ti-tré',
    sonido: '23',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventiquattro',
    espanol: 'veinticuatro',
    pista: 'ven-ti-cuát-tro',
    sonido: '24',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'venticinque',
    espanol: 'veinticinco',
    pista: 'ven-ti-chín-cue',
    sonido: '25',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventisei',
    espanol: 'veintiséis',
    pista: 'ven-ti-séi',
    sonido: '26',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventisette',
    espanol: 'veintisiete',
    pista: 'ven-ti-sét-te',
    sonido: '27',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventotto',
    espanol: 'veintiocho',
    pista: 'ven-tót-to, sin la i',
    sonido: '28',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'ventinove',
    espanol: 'veintinueve',
    pista: 'ven-ti-nó-ve',
    sonido: '29',
    grupo: GrupoHabla.numeros,
  ),
  PalabraHablada(
    italiano: 'trenta',
    espanol: 'treinta',
    pista: 'trén-ta',
    sonido: '30',
    grupo: GrupoHabla.numeros,
  ),
];
